### ISSUE TITLE
bad level 003

### ISSUE THREAD

**Issue by lspacenl** [the-butterfly-effect/tbe#282]
I managed to win level 003 with just 1 ramp
![003](https://cloud.githubusercontent.com/assets/16564496/15773909/e9f4b356-2979-11e6-8875-abb76d755c0f.png)

**Comment by Wuzzy2** [comment]
I can't think of an easy way how to fix this right now.

But I don't think this is a serious issue here, since this level is very easy anyways, so this variant solution does not really matter. But of course, if you have an idea to to improve this level (without making it too ugly), please share!

@kaa-ching, your thoughts?

**Comment by kaa-ching** [comment]
This level has given me enough headaches as is...
I've updated it for various exploits numerous times already.

It was one of the first levels we made, based on a children's game. I'm not really attached to it.
As far as I'm concerned, we move it to the attic.

**Comment by Wuzzy2** [comment]
Yeah, I don't thinik we should try to make each and every level completely free of alternate solutions, especially not the easy and early levels.

Alternate (easier) solutions for late levels are much more important IMO.

I vote for keeping this level, but I don't have strong feelings about it.

**Comment by lspacenl** [comment]
ok, move it to the attic. That's where the inspiration is too.
