### ISSUE TITLE
broken level ring the bell

### ISSUE THREAD

**Issue by lspacenl** [the-butterfly-effect/tbe#283]
Level ring the bell is broken. Or is it picnic1? This is unclear.
I can't place the arc close enough to the floor, a slight sill remains for the coke bottle to get stuck on. 

When trying to place it it looks ok but when I release the mouse button a cross appears.. This is not due to my shaking hand.

**Comment by Wuzzy2** [comment]
Not a bug, the level is solvable, you just haven't figured out how.
The way you tried it is obviously not the way to solve it. :P
I have found a nice solution, and it does not require pixel-perfect placement.

As for the other comment: In TBE, the bottom of every level has an invisible floor on which objects collide. It is roughly below the height of the grass for this level. That's why you sometimes get a cross. Yes, this is confusing, there's an issue about that: #92.
