### ISSUE TITLE
Bad level: Jumping Around 2

### ISSUE THREAD

**Issue by lspacenl** [the-butterfly-effect/tbe#284]
The ball lacks energy, or the placing of the spring is way too critical.
B.t.w. This is a compliment to the situation because how would a spring add energy to the bounce? All it does is introduce more friction
Also it is very hard to pick up the spring the coils are so thin you easily click in between

**Comment by Wuzzy2** [comment]
The level is solvable (all levels in Milestone B are solvable), but the placement of the spring is kinda annoying, I totally agree. It is very sensitive to small changes.

Hint: You can try many times quickly in row if you use shortcuts (`F` for fast forward, `Shift+F` for really fast forward, `R` for reset)

It may be a general problem of the spring that it is not quite fun to use as a trampoline-like object, especially since it is loose.

@kaa-ching: It seems the level becomes less WTF when `SpringConstant` is set to 300.
I will push a fix for this soon.

I will also push a fix for the spring pick-up problem soon, that one is easy to fix.
